# Generated by Django 4.1.2 on 2022-10-10 22:35

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=2000, verbose_name='name_eng')),
                ('image_url', models.CharField(max_length=2000, verbose_name='image_url')),
                ('subcategory_eng', models.CharField(max_length=2000, verbose_name='subcategory_eng')),
            ],
        ),
        migrations.CreateModel(
            name='searche_history',
            fields=[
                ('theme', models.CharField(max_length=300)),
                ('spec', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('arguments', picklefield.fields.PickledObjectField(editable=False)),
                ('search_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='userChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tot.theme')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('specs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tot.specs')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tot.theme')),
            ],
        ),
    ]
