# Generated by Django 4.1.2 on 2022-10-10 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='searche_history',
            new_name='search_history',
        ),
    ]
