# Generated by Django 4.1.2 on 2022-10-11 07:03

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0002_rename_searche_history_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_history',
            name='arguments',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
