# Generated by Django 4.1.2 on 2022-10-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0003_alter_search_history_arguments'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_history',
            name='choice',
            field=models.IntegerField(null=True),
        ),
    ]
