# Generated by Django 4.1.2 on 2022-10-11 21:10

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0004_search_history_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_history',
            name='options',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
