# Generated by Django 4.1.2 on 2022-10-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0005_search_history_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='spec',
            field=models.CharField(max_length=2000, null=True, verbose_name='spec'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='theme',
            field=models.CharField(max_length=2000, null=True, verbose_name='theme'),
        ),
    ]
