# Generated by Django 4.1.2 on 2022-10-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0006_clothes_spec_clothes_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specs',
            name='theme',
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.DeleteModel(
            name='specs',
        ),
        migrations.DeleteModel(
            name='theme',
        ),
    ]
