# Generated by Django 4.1.2 on 2022-10-18 00:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0008_theme_spec_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_history',
            name='saved_for_later',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), null=True, size=None),
        ),
    ]
