# Generated by Django 4.1.2 on 2022-10-18 00:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0010_userchoice_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_history',
            name='saved_for_later',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, null=True, size=None),
        ),
    ]
