# Generated by Django 4.1.2 on 2022-10-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0018_alter_search_history_saved_for_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='product_url',
            field=models.CharField(max_length=2000, null=True, verbose_name='product_url'),
        ),
    ]
