# Generated by Django 4.1.2 on 2022-10-18 21:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0019_clothes_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_history',
            name='saved_for_later_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), default=list, null=True, size=10),
        ),
    ]
