# Generated by Django 4.1.2 on 2022-10-25 23:58

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0020_search_history_saved_for_later_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='brand',
            field=models.CharField(max_length=2000, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='colour',
            field=models.CharField(max_length=2000, null=True, verbose_name='colour'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.CharField(max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='search_history',
            name='arguments_brand',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='search_history',
            name='arguments_colour',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
