# Generated by Django 4.1.2 on 2022-11-02 04:00

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0021_clothes_brand_clothes_colour_clothes_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_history',
            name='df',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
