# Generated by Django 4.1.2 on 2022-11-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tot', '0022_search_history_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
